name: github actions to github pages

on:
  push:
    branches:
    - main
    paths:
    - 'index.html'

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4

    - name: checking the files
      uses: super-linter/super-linter@v7.3.0